"use client";

import { useState } from "react";
import { ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Panel } from "@/components/shared/panel";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { api } from "@/lib/api";
import type { RagResponse } from "@/lib/types";

export function CompatibilityPage({ view }: { view: "organize" | "thesis-check" }) { const organize = view === "organize"; const [path, setPath] = useState(""); const [result, setResult] = useState<RagResponse | null>(null); const [approved, setApproved] = useState(false); const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); try { setResult(await api<RagResponse>(`/integrations/agent-workspace/${organize ? "organize" : "thesis-check"}`, { method: "POST", body: JSON.stringify({ path }) })); } catch { toast.error("The bridge request could not be completed."); } finally { setBusy(false); } }; const execute = async () => { if (!result?.approval_token) return; setBusy(true); try { setResult(await api<RagResponse>("/integrations/agent-workspace/organize/execute", { method: "POST", body: JSON.stringify({ path, approval_token: result.approval_token }) })); } finally { setBusy(false); } }; const title = organize ? "File Organizer" : "Thesis Check"; return <div className="grid gap-4 xl:grid-cols-[minmax(360px,.8fr)_minmax(0,1.2fr)]"><Panel title={title} eyebrow="Personal agent bridge"><ShieldCheck className="mb-4 text-emerald-400" size={28}/><p className="mb-5 text-sm leading-6 text-muted-foreground">{organize ? "Create a dry-run organization plan. File operations remain blocked until you explicitly confirm the server-issued plan." : "Run thesis structure and reference checks. This route produces reports and never edits thesis source files."}</p><Input value={path} onChange={(event) => setPath(event.target.value)} placeholder={organize ? "workspace/papers/to-organize" : "workspace/thesis/thesis.md"}/><Button className="mt-3 w-full" disabled={busy || !path.trim()} onClick={run}>{busy ? "Checking..." : organize ? "Preview dry-run plan" : "Run thesis check"}</Button>{organize && result?.approval_token && <div className="mt-4 rounded-md border border-amber-400/30 bg-amber-400/10 p-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={approved} onChange={(event) => setApproved(event.target.checked)} className="size-4 accent-emerald-400"/>I approve this one-time plan.</label><ConfirmDialog trigger={<Button className="mt-3 w-full" disabled={!approved || busy}>Confirm and execute</Button>} title="Execute approved organization plan?" description="The server will validate the dry-run approval token again before any operation is attempted." onConfirm={execute}/></div>}</Panel><Panel title="Bridge result" eyebrow={organize ? "Safe operation preview" : "Report status"}><pre className="max-h-[620px] overflow-auto whitespace-pre-wrap break-words font-mono text-xs leading-5">{result ? JSON.stringify(result, null, 2) : "Choose a workspace-relative path to begin."}</pre></Panel></div>; }
