"use client";

import { useState } from "react";
import { useDropzone } from "react-dropzone";
import { FileText, FolderInput, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Panel } from "@/components/shared/panel";
import { upload, api } from "@/lib/api";
import { errorMessage } from "@/lib/types";

export function ImportPage() {
  const [files, setFiles] = useState<File[]>([]); const [collection, setCollection] = useState("personal"); const [path, setPath] = useState(""); const [busy, setBusy] = useState(false); const [result, setResult] = useState<unknown>(null);
  const dropzone = useDropzone({ multiple: true, onDrop: (accepted) => setFiles(accepted), accept: { "application/pdf": [".pdf"], "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"], "text/markdown": [".md"], "text/plain": [".txt"], "application/vnd.openxmlformats-officedocument.presentationml.presentation": [".pptx"] } });
  const importFiles = async () => { if (!files.length) return; setBusy(true); try { const form = new FormData(); files.forEach((file) => form.append("files", file)); form.append("collection", collection); const value = await upload<unknown>("/kb/upload", form); setResult(value); toast.success(`${files.length} file(s) queued for indexing`); } catch (error) { toast.error(errorMessage(error)); } finally { setBusy(false); } };
  const importPath = async () => { if (!path.trim()) return; setBusy(true); try { const value = await api<unknown>("/kb/ingest", { method: "POST", body: JSON.stringify({ path, collection }) }); setResult(value); toast.success("Local path submitted for safe ingestion"); } catch (error) { toast.error(errorMessage(error)); } finally { setBusy(false); } };
  return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(360px,.8fr)]"><Panel title="Add knowledge sources" eyebrow="Import"><div {...dropzone.getRootProps()} className={`grid min-h-64 place-items-center rounded-lg border-2 border-dashed p-6 text-center transition-colors ${dropzone.isDragActive ? "border-emerald-400 bg-emerald-400/10" : "border-border bg-muted/20 hover:border-emerald-400/50"}`}><input {...dropzone.getInputProps()}/><div><UploadCloud className="mx-auto mb-3 text-emerald-400" size={32}/><h3 className="text-sm font-semibold">Drop documents here</h3><p className="mt-1 text-sm text-muted-foreground">PDF, DOCX, PPTX, Markdown, and text files</p><Button variant="outline" size="sm" className="mt-4">Browse files</Button></div></div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input value={collection} onChange={(event) => setCollection(event.target.value)} placeholder="Collection name"/><Button disabled={busy || !files.length} onClick={importFiles}>{busy ? "Indexing..." : "Import selected"}</Button></div>{files.length > 0 && <div className="mt-4 divide-y rounded-md border">{files.map((file) => <div key={`${file.name}-${file.size}`} className="flex items-center gap-3 px-3 py-2 text-sm"><FileText size={15} className="text-emerald-400"/><span className="flex-1 truncate">{file.name}</span><span className="font-mono text-xs text-muted-foreground">{Math.ceil(file.size / 1024)} KB</span></div>)}</div>}</Panel><div className="space-y-4"><Panel title="Import a workspace path" eyebrow="Local source"><p className="mb-4 text-sm leading-6 text-muted-foreground">The API resolves and validates local paths against its configured workspace policy.</p><div className="flex gap-2"><Input value={path} onChange={(event) => setPath(event.target.value)} placeholder="workspace/papers"/><Button size="icon" disabled={busy || !path.trim()} onClick={importPath}><FolderInput size={17}/></Button></div></Panel><Panel title="Indexing status" eyebrow="Result"><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words font-mono text-xs leading-5 text-muted-foreground">{result ? JSON.stringify(result, null, 2) : "Choose files or a local path to begin."}</pre></Panel></div></div>;
}
