"use client";

import { useState } from "react";
import { BookOpenCheck, FolderInput } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Panel } from "@/components/shared/panel";
import { api } from "@/lib/api";
import type { RagResponse } from "@/lib/types";

export function PaperReadingPage() { const [topic, setTopic] = useState(""); const [path, setPath] = useState(""); const [result, setResult] = useState<RagResponse | null>(null); const [busy, setBusy] = useState(false); const run = async (endpoint: string, body: object) => { setBusy(true); try { setResult(await api<RagResponse>(endpoint, { method: "POST", body: JSON.stringify(body) })); } finally { setBusy(false); } }; return <div className="grid gap-4 xl:grid-cols-2"><Panel title="Five-role research crew" eyebrow="Reader · Method · Experiment · Critic · Writer"><p className="mb-4 text-sm text-muted-foreground">Generate a grounded synthesis from the indexed academic collection.</p><div className="flex gap-2"><Input value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="Topic or paper question"/><Button disabled={busy || !topic.trim()} onClick={() => run("/agents/crew/run", { topic, top_k: 8 })}><BookOpenCheck/>Run crew</Button></div>{result?.steps?.length ? <ol className="mt-4 space-y-2">{result.steps.map((step, index) => <li key={index} className="rounded-md border p-3 text-sm"><b>{step.agent ?? step.task ?? step.tool_name}</b><span className="ml-2 text-xs text-emerald-400">Completed</span></li>)}</ol> : null}</Panel><Panel title="Batch paper reading" eyebrow="Agent workspace bridge"><p className="mb-4 text-sm text-muted-foreground">Use a safe workspace-relative folder. Notes are exported without modifying the source papers.</p><div className="flex gap-2"><Input value={path} onChange={(event) => setPath(event.target.value)} placeholder="workspace/papers"/><Button size="icon" disabled={busy || !path.trim()} onClick={() => run("/integrations/agent-workspace/read-papers", { path })}><FolderInput size={17}/></Button></div>{result?.workflow?.length ? <div className="mt-4 space-y-2">{result.workflow.map((paper) => <div key={paper.file_name} className="rounded-md border p-3 text-sm"><b>{paper.title}</b><p className="mt-1 text-xs text-muted-foreground">{paper.year ?? "Unknown year"} · {paper.status} · {paper.completed_roles.join(" · ")}</p></div>)}</div> : null}</Panel>{result && <Panel title="Research synthesis" eyebrow="Output" className="xl:col-span-2"><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words font-mono text-xs leading-5">{result.final_report ?? result.answer ?? JSON.stringify(result, null, 2)}</pre></Panel>}</div>; }
